name: ðŸš€ Deploy website on push to main

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy to InfinityFree (badri.name.np)
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftpupload.net           # âœ… no  prefix
          username: if0_38161098
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /badri.name.np/htdocs/
          exclude: |
            **/.git*
            **/.github*
            **/README.md
            **/LICENSE
